FROM daskdev/dask:2023.4.0-py3.9


RUN apt-get update --allow-releaseinfo-change -y
RUN apt-get upgrade --fix-missing -y
RUN apt-get install --no-install-recommends git build-essential python3-dev libpq-dev -y --fix-missing && \
    pip install -U pip

LABEL org.opencontainers.image.source = "https://github.com/quanted/nta_app"

WORKDIR /src/nta_app
COPY . /src/nta_app

RUN conda create --name pyenv python=3.9.13

RUN conda run -n pyenv --no-capture-output pip install -r /src/nta_app/requirements.txt
RUN conda run -n pyenv --no-capture-output python --version

ENV PATH "/src:/src/nta_app:/src/nta_flask:${PATH}"
ENV PYTHONPATH "/src:/src/nta_app:/src/nta_flask:${PYTHONPATH}"

CMD ["conda", "run", "-n", "pyenv", "--no-capture-output", "dask-worker", "dask-scheduler:8786"]