name: Code-analysis

on:
  push:
    branches: [ dev, add-sonarqube-integration ]


jobs:
  code-scan:
    name: code-scan
    runs-on: th870
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
